version: '3.7'

services: 
  iris:
    init: true
    build:
      context: .
    hostname: iris
    ports:
    - "1972:1972"
    - "52773:52773"
    command:
      --check-caps false
    environment:
    - TZ=JST-9
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    volumes:
    - ./ext:/home/irisowner/ext
    - ./misc:/home/irisowner/misc
    - ./UserCPF:/home/irisowner/cpf
